apiVersion: apps/v1
kind: Deployment
metadata:
  name: okteto-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okteto-sample
  template:
    metadata:
      labels:
        app: okteto-sample
    spec:
      containers:
      - image: okteto.dev/okteto-sample:latest
        name: okteto-sample

---

apiVersion: v1
kind: Service
metadata:
  name: okteto-sample
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: okteto-sample
